```{r, echo=FALSE}
## Compute QALYs

MI_util <- 0.812
SE_util <- 0.9
Comp_util <- 0.92

MI_reduct <- 1 - MI_util
SE_reduct <- 1 - SE_util
Comp_reduct <- 1 - Comp_util

qaly_A <- compute_cost(1, -MI_reduct, 0.1, -SE_reduct, 0.1, -Comp_reduct, 0.3)
qaly_B <- compute_cost(1, -MI_reduct, 0.035, -SE_reduct, 0.04, -Comp_reduct, 0.1)
qaly_C <- compute_cost(1, -MI_reduct, 0.02, -SE_reduct, 0.003, -Comp_reduct, 0.05)

qaly_A <- qaly_A * ly_A
qaly_B <- qaly_B * ly_B
qaly_C <- qaly_C * ly_C
```

## Compare treatments
```{r, echo=FALSE}
results <- data.frame(Treatment=c("A", "B", "C"),
                      Lifyears=c(ly_A, ly_B, ly_C),
                      QALYs=c(qaly_A, qaly_B, qaly_C),
                      Cost=c(cost_A, cost_B, cost_C))
treatment_table <- results[order(results$Cost, decreasing = FALSE),]
print(treatment_table)
```

## Treatment A is 1st order dominated
```{r, echo=FALSE}
treatment_table <- treatment_table[c(1,3),]
print(treatment_table)
```

## Compute ICERS for B and C
The ICUR for cost per QALY is calculated by
$$ICER = \frac{Cost_{C} - Cost_{B}}{QALY_{C} - QALY_{B}}$$

The ICER for cost per lifyear added is calculated by
$$ICER = \frac{Cost_C - Cost_B}{Lifeyear_C - Lifeyear_B}$$

The results below are the cost per QALY and cost per Lifeyear.
```{r, echo=FALSE}
ICER_QALY <- compute_icer(cost_B, cost_C, qaly_B, qaly_C)
ICER_LY <- compute_icer(cost_B, cost_C, ly_B, ly_C)

ICER_table <- data.frame(QALY=ICER_QALY, Lifeyear=ICER_LY)
print(ICER_table)
```


```{r, echo=FALSE, eval=FALSE}
## Probablistic sensitivity analysis
require(ggplot2)

# Compute costs for A
n=1e3
sens_cost_A <- sensitivity(2500, 50000, 0.1, 3000, 0.1, 16500, 0.3, n=n)
sens_cost_B <- sensitivity(5300, 50000, 0.035, 4000, 0.04, 3000, 0.1, n=n)
sens_cost_C <- sensitivity(16000, 50000, 0.02, 2300, 0.003, 3500, 0.05, n=n)

sens_qaly_A <- ly_A *sensitivity(1, -MI_reduct, 0.1, -SE_reduct, 0.1, -Comp_reduct, 0.3, n=n)
sens_qaly_B <- ly_B * sensitivity(1, -MI_reduct, 0.035, -SE_reduct, 0.04, -Comp_reduct, 0.1, n=n)
sens_qaly_C <- ly_C * sensitivity(1, -MI_reduct, 0.02, -SE_reduct, 0.003, -Comp_reduct-0.1, 0.05, n=n)

labels <- rep("A", 3*n)
labels[n:(2*n)] <- "B"
labels[(2*n):(3*n)] <- "C"

sensitivity_analysis <- data.frame(Cost=c(sens_cost_A, sens_cost_B, sens_cost_C),
                                  QALYs=c(sens_qaly_A, sens_qaly_B, sens_qaly_C),
                                  Treatment=labels)
```

```{r, echo=FALSE, eval=FALSE}
ggplot(data=sensitivity_analysis, aes(x=QALYs, y=Cost, color=Treatment)) +
  geom_point(alpha=0.5) + 
  labs(title="Cost vs QALYs")
```

```{r, echo=FALSE, eval=FALSE}
sens_analysis <- data.frame(Cost=c(sens_cost_A, sens_cost_B, sens_cost_C),
                            Treatment=labels)

ggplot(sens_analysis, aes(x=Cost, fill=Treatment)) + 
  geom_histogram(alpha=0.5, position="identity") +
  labs(title="Treatment cost distributions")
```

```{r, echo=FALSE, eval=FALSE}
library(devtools)
library(digest)
source_url("https://raw.github.com/low-decarie/FAAV/master/r/stat-ellipse.R")

df <- data.frame(Cost=(sens_cost_C - sens_cost_B),
                 QALYs=(sens_qaly_C - sens_qaly_B))

ggplot(df, aes(QALYs, Cost)) +
  geom_point(alpha=0.25) +
  labs(title="Incremental sensitivity analysis", x="Incremental cost", y="Incremental QALY") + 
  stat_ellipse() + 
  geom_hline(yintercept=0) + geom_vline(xintercept=0) + 
  geom_point(aes(x=mean(QALYs), y=mean(Cost)), col="red", size=3)
```